modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC-BY-NC-SA-4.0"

[[dependencies.butterbee]]
modId = "neoforge"
type = "required"
mandatory = true
versionRange = "[1,)"

[[dependencies.butterbee]]
modId = "vanillabackport"
type = "required"
mandatory = true
versionRange = "[1.1.5.1,)"

[[dependencies.butterbee]]
modId = "clifftree"
type = "optional"
versionRange = "[3.1.0,)"

[[dependencies.butterbee]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"

[[mods]]
modId = "butterbee"
version = "1.0.4"
displayName = "ButterBee"
description = "Populates biomes of the world with diverse new animal variants"
logoFile = "pack.png"
displayURL = "https://modrinth.com/project/butterbee"
credits = "Contributors: Evergreene"
authors = "Konci"
